### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [1AICHA/TeaCozy#3]
Overall met expectations.

Good structure.  The project didn't have any major errors.  The issues are minor in nature and more about web practices.

To prepare you for the final projects, look at media queries. See if you can make this site fit inside of a mobile device by using one. You will be doing this heavily in your final projects.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

**Comment by 1AICHA** [comment]
Thanks for your feedback! I will definitely take a look at media queries.
